# Étape de construction
FROM node:18 AS build

WORKDIR /app

# Copier les fichiers package.json et installer les dépendances
COPY package.json package-lock.json ./
RUN npm install

# Copier tous les fichiers du projet
COPY . .

# Exposer le port 5173 pour accéder à l'application depuis le navigateur
EXPOSE 5173

# Lancer Vite en mode développement
CMD ["npm", "run", "dev"]
