# Stage 1: Build React app
FROM node:18 AS build

WORKDIR /app
COPY . .

RUN npm install
RUN npm run build

# Stage 2: Serve the app using a lightweight server
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]
