version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Exposing frontend port
    environment:
      - VITE_BACKEND_URL=http://backend:5000  # You can set environment variables if needed
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Exposing backend port
    environment:
      - DB_HOST=db  # MySQL container host for backend
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ping
      - JWT_SECRET=your_secret_key
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ping
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
