# Use official Python image
FROM python:3.10

# Set the working directory
WORKDIR /app

# Copy the Flask app files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose Flask API port
EXPOSE 5001

# Start the Flask app
CMD ["python", "app.py"]
